---
- name: Install main packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - gcc
    - make
    - vim
    - curl
    - less
    - git
    - bash-completion
    - tmux
    - htop
    - atop
    - ncdu
    - iotop
    - dstat
    - fail2ban
    - neofetch
    - openssh-server
    - unrar
    - ranger
