---
- name: Include vars
  include_vars:
    file: vars/ssh_keys/authorized_keys.yml

- name: Create authorized_keys file
  blockinfile:
    dest: /home/{{ username | lower }}/.ssh/authorized_keys
    create: yes
    group: "{{ username | lower }}"
    owner: "{{ username | lower }}"
    mode: 0600
    block: |
      {{ authorized_keys }}
